version: '2'
services:
  nginx:
    depends_on:
      - fe
    container_name: nginx
    build: nginx/.
    image: mpr/nginx
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    volumes:
    - /var/www/static/mpr:/var/www/static/mpr
    domainname: meuportaretrato.com
  fe:
    container_name: fe
    build: .
    image: mpr/admin
    ports:
      - "8282:8282"
    environment:
      profile: prd
    stdin_open: true
    tty: true
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    domainname: meuportaretrato.com.br