version: '2'
services:
  fe:
    ports:
      - "8080:8080"
    image: mpr/admin
    environment:
      profile: dev
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    domainname: meuportaretrato.com.br