version: '2'
services:
  jobs-hml:
    ports:
      - "8080:8080"
    image: mpr/admin
    environment:
      profile: hml
    stdin_open: true
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    domainname: meuportaretrato.com.br