server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    locale: pt_BR
    locale-resolver: fixed
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mpr:
  wsApi: http://api.meuportaretrato.com
  wsUser: cliente.admin@meuportaretrato.com
  wsPass: admin@*753951*


logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG
