server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    locale: pt_BR
    locale-resolver: fixed

mpr:
#wsApi: api.meuportaretrato.com
  wsApi: api.meuportaretrato.com:8181
  wsUser: cliente.admin@meuportaretrato.com
  wsPass: admin@*753951*


logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    br:
      com:
        mpr: DEBUG
